[general]
database_url = "postgres://user:pass@localhost/db"
publicbase_url = "https://YOUR_DOMAIN"
telegram_token = "YOUR_TELEGRAM_TOKEN"
admin_chat_id = 000000000
uuid_namespace = "00000000-0000-0000-0000-000000000000"

[payments]
base_price = 000

[payments.betatransfer]
public_key = "YOUR_PUBLIC_KEY"
secret_key = "YOUR_SECRET_KEY"
webhook_port = 8080
ip_whitelist = [
    "0.0.0.0"
]

[vpn]
template_path = "templates/config.yaml"

# ==================== НОДА 1 ====================

[[vpn.nodes]]
name = "NAME"
ip = "YOUR_IP"

[vpn.nodes.xui]
base_url = "YOUR_3XUI_URL"
api_token = "YOUR_3XUI_API_TOKEN"

[vpn.nodes.vless]
inbound_id = 1
port = 443
public_key = "YOUR_PUBLIC_KEY"
short_id = ["YOUR_SHORT_IDs"]
sni = "YOUR_DOMAIN"
flow = ""

[vpn.nodes.hysteria2]
inbound_id = 2
port = 443
sni = "YOUR_DOMAIN"
obfs_password = "YOUR_PASSWORD"

# ==================== НОДА 2 ====================

[[vpn.nodes]]
name = "NAME"
ip = "YOUR_IP"

[vpn.nodes.xui]
base_url = "YOUR_3XUI_URL"
api_token = "YOUR_3XUI_API_TOKEN"

[vpn.nodes.vless]
inbound_id = 1
port = 443
public_key = "YOUR_PUBLIC_KEY"
short_id = ["YOUR_SHORT_IDs"]
sni = "YOUR_DOMAIN"
flow = ""

[vpn.nodes.hysteria2]
inbound_id = 2
port = 443
sni = "YOUR_DOMAIN"
obfs_password = "YOUR_PASSWORD"

